### ISSUE TITLE
Lower performance on Youcook2

### ISSUE THREAD

**Issue by Lin-Yijie** [yyuncong/TempCLR#3]
Dear authors, I have evaluated your checkpoint on Youcook2. However, the results are much lower than what you reported. Is this correct?

### Checkpoint Videoclip
**Clip-caption**
30fps R@1: 0.2237 - R@5: 0.5030 - R@10: 0.6256 - Median R: 5.0
**Full-video**
Caption Average:
R@1: 0.7454 - R@5: 0.9450 - R@10: 0.9794
DTW:
R@1: 0.5596 - R@5: 0.8991 - R@10: 0.9633
OTAM
R@1: 0.7867 - R@5: 0.9748 - R@10: 0.9862

### Checkpoint runs/checkpoint_allparameters_DTW.pt

**Clip-caption**
R@1: 0.2118 - R@5: 0.4582 - R@10: 0.5880 - Median R: 7.0

**Full-video**
Caption Average:
R@1: 0.7408 - R@5: 0.9289 - R@10: 0.9679
DTW:
R@1: 0.4312 - R@5: 0.8257 - R@10: 0.9037
OTAM
R@1: 0.6628 - R@5: 0.9289 - R@10: 0.9794

**Comment by yyuncong** [comment]
This is expected.

We mentioned in the appendix that only finetuning the layernorms proves to be a more effective strategy (works in both video retrieval and action step localization), and the majority of the results we reported are from the layernorm checkpoints. We also stated in the readme that the allparameter checkpoint is slightly better *only* for zero-shot action step localization. 

We just updated the readme file to make this clear. For this task, we recommend utilizing the other two checkpoints (especially the OTAM one).
